### ISSUE TITLE
名前がダサすぎる

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/event-to-twitter-list#1]
「event-to-twitter-list」はあまりにも安直過ぎる...

かっこいいのを考えます．
皆さんにも挙げていただけると嬉しいです．

**Comment by takanakahiko** [comment]
- connopass 以外にも対応したい #6 (ので，connopassに引っ掛けたネーミングは厳しい)
- 長すぎるとレイアウトとかで困りそう

**Comment by kkosuge** [comment]
単機能のツールであれば分かりやすさ全投資で「イベントページからツイッターのリストを作るやつ」くらいでもいいのではと思いました。
例えば Twitter のリストのデータからポータルサイトを作るというような大きな野望を抱えている場合であれば、かっこよさ重視してサイト名考えたいですが。

**Comment by takanakahiko** [comment]
大きな野望がないです！大きな野望がないので「イベントページからツイッターのリストを作るやつ」にします！

**Comment by kkosuge** [comment]
一応、この名前は「リツイート直後のツイートを表示するやつ」さんリスペクトです 🐦 
https://retweets.azurewebsites.net/?lang=ja
