### ISSUE TITLE
デザインがダサい

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/event-to-twitter-list#10]
![image](https://user-images.githubusercontent.com/10114717/60400185-a6b36b80-9bab-11e9-9ae6-9deaf9f8dd10.png)

![image](https://user-images.githubusercontent.com/10114717/60400182-969b8c00-9bab-11e9-91b9-912bae74125f.png)

![image](https://user-images.githubusercontent.com/10114717/60400197-c054b300-9bab-11e9-8120-3050946beeb0.png)

**Comment by kkosuge** [comment]
やるべき事が小さくまとまっててよいと思うので、Login, Event url, List name となっているタイトル文言を

① Twitterアカウントでログイン
② イベントページのURLを入力
③ 作成する Twitter リストの名前を入力

３ステップとすれば、一瞬見ただけで完全に理解できそう

**Comment by takanakahiko** [comment]
ありがとうございます！
項目名はそれに変えようと思います！

**Comment by takanakahiko** [comment]
だいぶマシになったので閉じます

![image](https://user-images.githubusercontent.com/10114717/60574329-64a94600-9db4-11e9-9534-e6a000c4b378.png)
