### ISSUE TITLE
TwiPla のイベントも対応したい

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/event-to-twitter-list#6]
簡単そうだが，優先度は低め

**Comment by saitoeku3** [comment]
まだ誰も手を付けていなかったらやりたいです〜

**Comment by takanakahiko** [comment]
@saitoeku3 頼みます...! 
twipla.ts で URL 投げたらtwitter_id 帰ってくるfunctionがexportされてたら最高です！
